### ISSUE TITLE
Move this repository under Microsoft Docs

### ISSUE THREAD

**Issue by syedhassaanahmed** [Azure/AzureDatabricksBestPractices#11]
Thank you for publishing this great set of Azure Databricks best practices. For the sake of this content's discoverability and consistency with other documentation, wouldn't it be better to move this repository under the [official Azure Databricks docs](https://docs.microsoft.com/en-us/azure/azure-databricks/)?

**Comment by swan-am-i** [comment]
Hi Syed, the docs team clarified that they want product documentation in the docs website and have a strict format and requirements and takes some time to publish. Where as this is a deployment guide based on real world strategic customer engagements that we need to update quite often.

**Comment by syedhassaanahmed** [comment]
@swan-am-i Thanks for clarifying. Is it possible for the docs team to link this repository from the Azure Databricks docs for discoverability?
